---
- name: 'Update APT package cache'
  apt:
    update_cache: yes
    upgrade: safe
  
- name: Install packages
  apt:
    package:
      - git
      - apt-transport-https
      - ca-certificates
      - wget
      - software-properties-common
      - gnupg2
      - curl
      - python3-pip
    state: present
